// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbproxy.proto

package go_micro_service_dbproxy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqSignup struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EncPasswd            string   `protobuf:"bytes,2,opt,name=encPasswd,proto3" json:"encPasswd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignup) Reset()         { *m = ReqSignup{} }
func (m *ReqSignup) String() string { return proto.CompactTextString(m) }
func (*ReqSignup) ProtoMessage()    {}
func (*ReqSignup) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{0}
}

func (m *ReqSignup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignup.Unmarshal(m, b)
}
func (m *ReqSignup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignup.Marshal(b, m, deterministic)
}
func (m *ReqSignup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignup.Merge(m, src)
}
func (m *ReqSignup) XXX_Size() int {
	return xxx_messageInfo_ReqSignup.Size(m)
}
func (m *ReqSignup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignup proto.InternalMessageInfo

func (m *ReqSignup) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqSignup) GetEncPasswd() string {
	if m != nil {
		return m.EncPasswd
	}
	return ""
}

type RespSignup struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSignup) Reset()         { *m = RespSignup{} }
func (m *RespSignup) String() string { return proto.CompactTextString(m) }
func (*RespSignup) ProtoMessage()    {}
func (*RespSignup) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{1}
}

func (m *RespSignup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignup.Unmarshal(m, b)
}
func (m *RespSignup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignup.Marshal(b, m, deterministic)
}
func (m *RespSignup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignup.Merge(m, src)
}
func (m *RespSignup) XXX_Size() int {
	return xxx_messageInfo_RespSignup.Size(m)
}
func (m *RespSignup) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignup.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignup proto.InternalMessageInfo

func (m *RespSignup) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespSignup) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReqSignin struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EncPasswd            string   `protobuf:"bytes,2,opt,name=encPasswd,proto3" json:"encPasswd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignin) Reset()         { *m = ReqSignin{} }
func (m *ReqSignin) String() string { return proto.CompactTextString(m) }
func (*ReqSignin) ProtoMessage()    {}
func (*ReqSignin) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{2}
}

func (m *ReqSignin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignin.Unmarshal(m, b)
}
func (m *ReqSignin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignin.Marshal(b, m, deterministic)
}
func (m *ReqSignin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignin.Merge(m, src)
}
func (m *ReqSignin) XXX_Size() int {
	return xxx_messageInfo_ReqSignin.Size(m)
}
func (m *ReqSignin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignin proto.InternalMessageInfo

func (m *ReqSignin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqSignin) GetEncPasswd() string {
	if m != nil {
		return m.EncPasswd
	}
	return ""
}

type RespSignin struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSignin) Reset()         { *m = RespSignin{} }
func (m *RespSignin) String() string { return proto.CompactTextString(m) }
func (*RespSignin) ProtoMessage()    {}
func (*RespSignin) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{3}
}

func (m *RespSignin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSignin.Unmarshal(m, b)
}
func (m *RespSignin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSignin.Marshal(b, m, deterministic)
}
func (m *RespSignin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSignin.Merge(m, src)
}
func (m *RespSignin) XXX_Size() int {
	return xxx_messageInfo_RespSignin.Size(m)
}
func (m *RespSignin) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSignin.DiscardUnknown(m)
}

var xxx_messageInfo_RespSignin proto.InternalMessageInfo

func (m *RespSignin) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespSignin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RespSignin) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReqUpdateToken struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateToken) Reset()         { *m = ReqUpdateToken{} }
func (m *ReqUpdateToken) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateToken) ProtoMessage()    {}
func (*ReqUpdateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{4}
}

func (m *ReqUpdateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateToken.Unmarshal(m, b)
}
func (m *ReqUpdateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateToken.Marshal(b, m, deterministic)
}
func (m *ReqUpdateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateToken.Merge(m, src)
}
func (m *ReqUpdateToken) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateToken.Size(m)
}
func (m *ReqUpdateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateToken.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateToken proto.InternalMessageInfo

func (m *ReqUpdateToken) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqUpdateToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RespUpdateToken struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespUpdateToken) Reset()         { *m = RespUpdateToken{} }
func (m *RespUpdateToken) String() string { return proto.CompactTextString(m) }
func (*RespUpdateToken) ProtoMessage()    {}
func (*RespUpdateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{5}
}

func (m *RespUpdateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespUpdateToken.Unmarshal(m, b)
}
func (m *RespUpdateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespUpdateToken.Marshal(b, m, deterministic)
}
func (m *RespUpdateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespUpdateToken.Merge(m, src)
}
func (m *RespUpdateToken) XXX_Size() int {
	return xxx_messageInfo_RespUpdateToken.Size(m)
}
func (m *RespUpdateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RespUpdateToken.DiscardUnknown(m)
}

var xxx_messageInfo_RespUpdateToken proto.InternalMessageInfo

func (m *RespUpdateToken) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ReqGetToken struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetToken) Reset()         { *m = ReqGetToken{} }
func (m *ReqGetToken) String() string { return proto.CompactTextString(m) }
func (*ReqGetToken) ProtoMessage()    {}
func (*ReqGetToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{6}
}

func (m *ReqGetToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetToken.Unmarshal(m, b)
}
func (m *ReqGetToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetToken.Marshal(b, m, deterministic)
}
func (m *ReqGetToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetToken.Merge(m, src)
}
func (m *ReqGetToken) XXX_Size() int {
	return xxx_messageInfo_ReqGetToken.Size(m)
}
func (m *ReqGetToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetToken.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetToken proto.InternalMessageInfo

func (m *ReqGetToken) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RespGetToken struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespGetToken) Reset()         { *m = RespGetToken{} }
func (m *RespGetToken) String() string { return proto.CompactTextString(m) }
func (*RespGetToken) ProtoMessage()    {}
func (*RespGetToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_353d095adafb115d, []int{7}
}

func (m *RespGetToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGetToken.Unmarshal(m, b)
}
func (m *RespGetToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGetToken.Marshal(b, m, deterministic)
}
func (m *RespGetToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGetToken.Merge(m, src)
}
func (m *RespGetToken) XXX_Size() int {
	return xxx_messageInfo_RespGetToken.Size(m)
}
func (m *RespGetToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGetToken.DiscardUnknown(m)
}

var xxx_messageInfo_RespGetToken proto.InternalMessageInfo

func (m *RespGetToken) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespGetToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RespGetToken) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSignup)(nil), "go.micro.service.dbproxy.ReqSignup")
	proto.RegisterType((*RespSignup)(nil), "go.micro.service.dbproxy.RespSignup")
	proto.RegisterType((*ReqSignin)(nil), "go.micro.service.dbproxy.ReqSignin")
	proto.RegisterType((*RespSignin)(nil), "go.micro.service.dbproxy.RespSignin")
	proto.RegisterType((*ReqUpdateToken)(nil), "go.micro.service.dbproxy.ReqUpdateToken")
	proto.RegisterType((*RespUpdateToken)(nil), "go.micro.service.dbproxy.RespUpdateToken")
	proto.RegisterType((*ReqGetToken)(nil), "go.micro.service.dbproxy.ReqGetToken")
	proto.RegisterType((*RespGetToken)(nil), "go.micro.service.dbproxy.RespGetToken")
}

func init() { proto.RegisterFile("dbproxy.proto", fileDescriptor_353d095adafb115d) }

var fileDescriptor_353d095adafb115d = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4f, 0xc2, 0x30,
	0x18, 0xc5, 0x87, 0x88, 0xca, 0xa7, 0x42, 0x6c, 0x3c, 0x2c, 0x8b, 0x07, 0x53, 0xc5, 0xc0, 0x65,
	0x07, 0xbd, 0x79, 0x24, 0x12, 0xaf, 0xa4, 0xc8, 0xdd, 0xb1, 0x7d, 0x21, 0x0d, 0xa1, 0x1d, 0xed,
	0x50, 0xfc, 0x83, 0xfc, 0x3f, 0x0d, 0x5b, 0x37, 0x6a, 0x32, 0x2b, 0x89, 0xde, 0xf6, 0xad, 0xaf,
	0xef, 0xf7, 0xb6, 0xbe, 0xc2, 0x79, 0x32, 0x4b, 0x95, 0xdc, 0x7c, 0x84, 0xa9, 0x92, 0x99, 0x24,
	0xfe, 0x5c, 0x86, 0x4b, 0x1e, 0x2b, 0x19, 0x6a, 0x54, 0x6f, 0x3c, 0xc6, 0xd0, 0xac, 0xd3, 0x11,
	0xb4, 0x19, 0xae, 0x26, 0x7c, 0x2e, 0xd6, 0x29, 0x09, 0xe0, 0x64, 0xad, 0x51, 0x89, 0x68, 0x89,
	0x7e, 0xe3, 0xba, 0xd1, 0x6f, 0xb3, 0x6a, 0x26, 0x57, 0xd0, 0x46, 0x11, 0x8f, 0x23, 0xad, 0xdf,
	0x13, 0xff, 0x20, 0x5f, 0xdc, 0xbd, 0xa0, 0x8f, 0x00, 0x0c, 0x75, 0x6a, 0x7c, 0x08, 0x1c, 0xc6,
	0x32, 0x29, 0x3c, 0x5a, 0x2c, 0x7f, 0x26, 0x3e, 0x1c, 0x2f, 0x51, 0xeb, 0x68, 0x8e, 0x66, 0x77,
	0x39, 0x5a, 0x11, 0xb8, 0xf8, 0x43, 0x84, 0xf1, 0x2e, 0x02, 0x17, 0xb5, 0x11, 0x2e, 0xa1, 0x95,
	0xc9, 0x05, 0x0a, 0xb3, 0xb7, 0x18, 0xec, 0x60, 0xcd, 0xef, 0xc1, 0x86, 0xd0, 0x61, 0xb8, 0x9a,
	0xa6, 0x49, 0x94, 0xe1, 0x4b, 0xae, 0x75, 0xa5, 0xab, 0x75, 0xa7, 0x3d, 0xe8, 0x6e, 0x53, 0xd9,
	0x26, 0x35, 0xd1, 0xe8, 0x00, 0x4e, 0x19, 0xae, 0x9e, 0x31, 0xfb, 0x95, 0x43, 0x19, 0x9c, 0x6d,
	0x1d, 0x2b, 0xed, 0x3f, 0x7c, 0xe9, 0xfd, 0x67, 0x13, 0x3a, 0x4f, 0xc3, 0xf1, 0xb6, 0x11, 0x93,
	0xa2, 0x20, 0xe4, 0x15, 0x2e, 0x46, 0x1b, 0x8c, 0xd7, 0x19, 0x4e, 0x35, 0x2a, 0x73, 0xb0, 0x37,
	0xe1, 0x4f, 0x45, 0x0a, 0xab, 0x16, 0x05, 0xb7, 0x2e, 0x51, 0xd9, 0x11, 0xea, 0xd5, 0x10, 0xb8,
	0xd8, 0x83, 0xc0, 0xc5, 0x3e, 0x04, 0x2e, 0xa8, 0x47, 0x16, 0x40, 0x4a, 0x82, 0xf5, 0xff, 0xfb,
	0x4e, 0x84, 0xa5, 0x0c, 0x06, 0x6e, 0x8e, 0x25, 0xa5, 0x1e, 0x99, 0x41, 0xd7, 0xc0, 0xaa, 0xa3,
	0xe9, 0x39, 0x49, 0xa5, 0x2c, 0xb8, 0x73, 0x63, 0x4a, 0x1d, 0xf5, 0x66, 0x47, 0xf9, 0x75, 0x7e,
	0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x59, 0x91, 0x28, 0xa2, 0xdf, 0x03, 0x00, 0x00,
}
